# Generated by Django 4.2.3 on 2023-07-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_advocate_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='company_id',
            new_name='company',
        ),
    ]
